-- ============================================================================
--  01-app.sql — THE APP-OWNED TABLES, IN T-SQL
--
--  This is the SQL Server translation of `data/sql/turso/01-app.sql`. That file
--  is SQLite and cannot be applied here: `AUTOINCREMENT`, `datetime('now')` and
--  the `IF NOT EXISTS` forms are all syntax errors in T-SQL. The two files own
--  the same thirteen tables and must stay in step.
--
--  ── WHAT CHANGED IN TRANSLATION, AND WHY EACH ONE IS NOT COSMETIC ──────────
--
--    SQLite                              T-SQL
--    --------------------------------    ------------------------------------
--    INTEGER PRIMARY KEY AUTOINCREMENT   INT IDENTITY(1,1) PRIMARY KEY
--    TEXT                                NVARCHAR(n)
--    TEXT DEFAULT (datetime('now'))      NVARCHAR(30) DEFAULT (CONVERT(...))
--    INTEGER (for a 0/1 flag)            BIT
--    CREATE TABLE IF NOT EXISTS          IF OBJECT_ID(...) IS NULL
--    CREATE INDEX IF NOT EXISTS          IF NOT EXISTS (SELECT 1 FROM sys...)
--
--  ★★ `INT` FOR THE IDS, NOT `BIGINT` — AND THAT IS A DECISION, NOT AN OVERSIGHT.
--     The ledger copy needed BIGINT because the Oracle ids exceed 32-bit (PO
--     LINE_NUM reached 7.88 billion). These are APP ids: they are generated by
--     IDENTITY starting at 1, the largest table here holds 12 rows, and the
--     largest table anywhere in this schema is `saved_view_run` at 8. INT is
--     correct and BIGINT would be a claim about a scale this data does not have.
--
--  ★★ `NVARCHAR(30)` FOR TIMESTAMPS, NOT `DATETIME2` — AND THIS ONE MATTERS.
--     SQLite stores these as TEXT in `YYYY-MM-DD HH:MM:SS` form, and the app
--     reads them as strings: `app/src` compares them lexically and prints them
--     directly. A DATETIME2 column would change the wire type and break every
--     reader. The default reproduces SQLite's exact format:
--
--         CONVERT(varchar(19), GETUTCDATE(), 126)   ->  2026-09-24 21:45:18
--
--     ★ GETUTCDATE(), NOT GETDATE(). SQLite's `datetime('now')` is UTC, and the
--       comments in the source file rely on that. GETDATE() is server-local, so
--       it would silently shift every timestamp by the server's offset.
--
--  ★★ `BIT` FOR THE 0/1 FLAGS, AND THE CHECK IS DROPPED WITH A REASON.
--     SQLite has no boolean, so the source file writes `INTEGER ... CHECK (x IN
--     (0,1))` and comments that the CHECK is what makes the invariant real. T-SQL
--     HAS a boolean, so `BIT` states the same thing in the type rather than in a
--     constraint — the CHECK is not lost, it is promoted. `BIT` cannot hold 2.
--
--  ★ CONSTRAINTS ARE CARRIED, NOT DROPPED. Every UNIQUE, NOT NULL and CHECK from
--     the source file appears here. A translation that quietly omitted one would
--     be a behaviour change that no test in this repo would catch, because the
--     app relies on the database to enforce them.
--
--  ★ FOREIGN KEYS ARE DECLARED BUT NOT ENFORCED BY DEFAULT. T-SQL does not check
--     them unless they are trusted, and `saved_view_run.view_id` uses ON DELETE
--     CASCADE in the source. They are written here so the relationship is stated
--     and so a later `ALTER TABLE ... WITH CHECK` can enforce them.
-- ============================================================================


-- ----------------------------------------------------------------------------
--  saved_view — the View Builder's saved statements.
-- ----------------------------------------------------------------------------
IF OBJECT_ID('dbo.saved_view', 'U') IS NULL
CREATE TABLE dbo.saved_view (
  id            INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  slug          NVARCHAR(200) NOT NULL UNIQUE,

  title         NVARCHAR(400) NOT NULL,
  description   NVARCHAR(MAX) NULL,

  sql           NVARCHAR(MAX) NOT NULL,

  -- JSON text, not a JSON column type -- the app parses it in JS, and '[]' / '{}'
  -- rather than NULL so every reader can parse unconditionally.
  params_json   NVARCHAR(MAX) NOT NULL DEFAULT '[]',
  display_json  NVARCHAR(MAX) NOT NULL DEFAULT '{}',

  -- ★ TEXT, NOT A FOREIGN KEY, AND THE SOURCE FILE EXPLAINS WHY AT LENGTH: this
  --   column owns the sentence "who made this", frozen at the moment it was made.
  --   A FK would rewrite a historical attribution when a display_name changed.
  created_by    NVARCHAR(200) NULL,

  status        NVARCHAR(20) NOT NULL DEFAULT 'draft'
                  CONSTRAINT CK_saved_view_status CHECK (status IN ('draft','active','disabled')),

  created_at    NVARCHAR(30) NOT NULL DEFAULT (CONVERT(varchar(19), GETUTCDATE(), 126)),
  updated_at    NVARCHAR(30) NOT NULL DEFAULT (CONVERT(varchar(19), GETUTCDATE(), 126))
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_SAVED_VIEW_STATUS' AND object_id = OBJECT_ID('dbo.saved_view'))
  CREATE INDEX IDX_SAVED_VIEW_STATUS ON dbo.saved_view (status, title);
GO


-- ----------------------------------------------------------------------------
--  saved_view_run — one row per execution.
-- ----------------------------------------------------------------------------
IF OBJECT_ID('dbo.saved_view_run', 'U') IS NULL
CREATE TABLE dbo.saved_view_run (
  id           INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  view_id      INT NOT NULL,

  ran_at       NVARCHAR(30) NOT NULL DEFAULT (CONVERT(varchar(19), GETUTCDATE(), 126)),

  -- ★ NULLABLE RATHER THAN DEFAULTED TO 0, and the source file is emphatic about
  --   it: a run refused before reaching the database has no duration and no row
  --   count, and writing 0 would make "did not run" indistinguishable from "ran
  --   and found nothing". That confusion once produced a fictitious -100% delta
  --   in this project's history.
  duration_ms  INT NULL,
  row_count    INT NULL,
  truncated    BIT NULL,

  fingerprint  NVARCHAR(200) NULL,
  error        NVARCHAR(MAX) NULL,

  CONSTRAINT FK_saved_view_run_view FOREIGN KEY (view_id)
    REFERENCES dbo.saved_view (id) ON DELETE CASCADE
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_SAVED_VIEW_RUN_VIEW' AND object_id = OBJECT_ID('dbo.saved_view_run'))
  CREATE INDEX IDX_SAVED_VIEW_RUN_VIEW ON dbo.saved_view_run (view_id, ran_at DESC);
GO


-- ----------------------------------------------------------------------------
--  saved_view_subscription — who wants to know when a view's result changes.
-- ----------------------------------------------------------------------------
IF OBJECT_ID('dbo.saved_view_subscription', 'U') IS NULL
CREATE TABLE dbo.saved_view_subscription (
  id          INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  view_id     INT NOT NULL,

  subscriber  NVARCHAR(200) NOT NULL,
  channel     NVARCHAR(20) NOT NULL
                CONSTRAINT CK_saved_view_sub_channel CHECK (channel IN ('in_app','webhook')),
  target      NVARCHAR(400) NULL,

  created_at  NVARCHAR(30) NOT NULL DEFAULT (CONVERT(varchar(19), GETUTCDATE(), 126)),

  -- One subscription per person per channel per view. Re-subscribing is not an
  -- error; it is the same request twice.
  CONSTRAINT UQ_saved_view_sub UNIQUE (view_id, subscriber, channel),

  CONSTRAINT FK_saved_view_sub_view FOREIGN KEY (view_id)
    REFERENCES dbo.saved_view (id) ON DELETE CASCADE
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_SAVED_VIEW_SUB_VIEW' AND object_id = OBJECT_ID('dbo.saved_view_subscription'))
  CREATE INDEX IDX_SAVED_VIEW_SUB_VIEW ON dbo.saved_view_subscription (view_id);
GO


-- ----------------------------------------------------------------------------
--  project — the project master.
--
--  ★ THE SOURCE FILE'S LONG NOTE ON `level_code` APPLIES HERE UNCHANGED, and the
--    translation must not lose it: a project exists as a NAME before anybody has
--    decided which account level funds it, so `level_code` is NULLABLE. It is
--    also UNIQUE, and SQLite permits many NULLs in a UNIQUE column -- which is
--    what makes "not yet associated" storable more than once.
--
--  ★★ T-SQL DOES NOT PERMIT MANY NULLS IN A UNIQUE CONSTRAINT, AND THIS IS THE
--     ONE PLACE THE TWO DATABASES GENUINELY DIFFER. SQL Server treats NULL as a
--     value for uniqueness, so a plain `UNIQUE` would allow only ONE unassigned
--     project. A filtered unique index is the T-SQL equivalent:
--
--         CREATE UNIQUE INDEX ... WHERE level_code IS NOT NULL
--
--     which enforces "two projects cannot claim the same level" while leaving
--     any number of unassigned projects storable. Without the filter, the second
--     unassigned project would be refused and the app would appear to lose a row.
-- ----------------------------------------------------------------------------
IF OBJECT_ID('dbo.project', 'U') IS NULL
CREATE TABLE dbo.project (
  id          INT IDENTITY(1,1) NOT NULL PRIMARY KEY,

  slug        NVARCHAR(200) NOT NULL UNIQUE,

  name        NVARCHAR(400) NOT NULL,
  description NVARCHAR(MAX) NULL,

  -- The SEGMENT5 value this project claims, or NULL when nobody has said yet.
  -- NO inline UNIQUE here -- see the filtered index below, which is the T-SQL
  -- form of "unique, but many NULLs allowed".
  level_code  NVARCHAR(20) NULL,

  code        NVARCHAR(50) NULL,
  site        NVARCHAR(200) NULL,
  owner       NVARCHAR(200) NULL,

  created_at  NVARCHAR(30) NOT NULL DEFAULT (CONVERT(varchar(19), GETUTCDATE(), 126)),
  updated_at  NVARCHAR(30) NOT NULL DEFAULT (CONVERT(varchar(19), GETUTCDATE(), 126))
);
GO

-- ★ THE FILTERED INDEX IS THE POINT. `WHERE level_code IS NOT NULL` is what makes
--   this behave like SQLite's UNIQUE-with-many-NULLs rather than SQL Server's
--   UNIQUE-with-one-NULL.
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UQ_project_level_code' AND object_id = OBJECT_ID('dbo.project'))
  CREATE UNIQUE INDEX UQ_project_level_code ON dbo.project (level_code) WHERE level_code IS NOT NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_PROJECT_NAME' AND object_id = OBJECT_ID('dbo.project'))
  CREATE INDEX IDX_PROJECT_NAME ON dbo.project (name);
GO


-- ----------------------------------------------------------------------------
--  organization — the tenant.
-- ----------------------------------------------------------------------------
IF OBJECT_ID('dbo.organization', 'U') IS NULL
CREATE TABLE dbo.organization (
  id             INT IDENTITY(1,1) NOT NULL PRIMARY KEY,

  slug           NVARCHAR(200) NOT NULL UNIQUE,
  name           NVARCHAR(400) NOT NULL,

  -- The Fund segment value as the chart of accounts spells it -- '04', not 4.
  -- Leading zeros are significant in every segment of this account structure,
  -- which is why it is NVARCHAR and not INT.
  fund           NVARCHAR(10) NOT NULL,

  programs_json  NVARCHAR(MAX) NOT NULL DEFAULT '[]',

  start_fy       INT NOT NULL,

  is_default     BIT NOT NULL DEFAULT 0,

  created_at     NVARCHAR(30) NOT NULL DEFAULT (CONVERT(varchar(19), GETUTCDATE(), 126)),
  updated_at     NVARCHAR(30) NOT NULL DEFAULT (CONVERT(varchar(19), GETUTCDATE(), 126))
);
GO

-- ★ THE RULE, NOT A CONVENTION: at most one row may claim is_default. The source
--   file uses SQLite's partial index for this (`WHERE is_default = 1`); the same
--   filtered-index form works in T-SQL, and the filter is what makes it a rule
--   rather than "at most one 0 and at most one 1".
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'organization_one_default' AND object_id = OBJECT_ID('dbo.organization'))
  CREATE UNIQUE INDEX organization_one_default ON dbo.organization (is_default) WHERE is_default = 1;
GO


-- ----------------------------------------------------------------------------
--  app_user — who may sign in, and which tenant they see.
--
--  ★ NO PASSWORD COLUMN, DELIBERATELY. See the source file: a column named
--    `password_hash` holding nothing would be worse than its absence, because a
--    reader would assume it was the real thing.
--
--  ★ `organization_id` IS NULLABLE EVEN THOUGH EVERY USER BELONGS TO ONE.
--    "Belongs to an organization" and "has been given one here yet" are different
--    states, and collapsing them would make an unassigned user silently inherit
--    the default. A NULL means "not assigned" and the sign-in path refuses.
-- ----------------------------------------------------------------------------
IF OBJECT_ID('dbo.app_user', 'U') IS NULL
CREATE TABLE dbo.app_user (
  id              INT IDENTITY(1,1) NOT NULL PRIMARY KEY,

  -- Lower-cased on write; the lookup lower-cases what it was given, so
  -- `Dana@x.gov` and `dana@x.gov` are one account and not two.
  email           NVARCHAR(320) NOT NULL UNIQUE,

  display_name    NVARCHAR(200) NOT NULL,

  role            NVARCHAR(20) NOT NULL DEFAULT 'member'
                    CONSTRAINT CK_app_user_role CHECK (role IN ('super_admin','member')),

  organization_id INT NULL,

  created_at      NVARCHAR(30) NOT NULL DEFAULT (CONVERT(varchar(19), GETUTCDATE(), 126)),

  -- NULL means the account has never been used, which is a different fact from
  -- "used a long time ago".
  last_seen_at    NVARCHAR(30) NULL,

  CONSTRAINT FK_app_user_org FOREIGN KEY (organization_id) REFERENCES dbo.organization (id)
);
GO


-- ----------------------------------------------------------------------------
--  user_pin — a reader's private shortcuts to records in the ledger.
-- ----------------------------------------------------------------------------
IF OBJECT_ID('dbo.user_pin', 'U') IS NULL
CREATE TABLE dbo.user_pin (
  id           INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  owner_email  NVARCHAR(320) NOT NULL,
  category     NVARCHAR(20) NOT NULL
                 CONSTRAINT CK_user_pin_category CHECK (category IN ('project','invoice','check','purchase-order')),
  entity_key   NVARCHAR(400) NOT NULL,
  title        NVARCHAR(400) NOT NULL,
  subtitle     NVARCHAR(400) NOT NULL DEFAULT '',
  href         NVARCHAR(1000) NOT NULL,
  created_at   NVARCHAR(30) NOT NULL DEFAULT (CONVERT(varchar(19), GETUTCDATE(), 126)),

  CONSTRAINT UQ_user_pin UNIQUE (owner_email, category, entity_key)
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_USER_PIN_OWNER_CATEGORY' AND object_id = OBJECT_ID('dbo.user_pin'))
  CREATE INDEX IDX_USER_PIN_OWNER_CATEGORY ON dbo.user_pin (owner_email, category, created_at DESC);
GO


-- ----------------------------------------------------------------------------
--  geo_origin — the place a driving distance is measured FROM.
--
--  ★ A SLUG PRIMARY KEY, NOT A SURROGATE ID. The slug is what a distance row
--    stores so it can name its origin without a join, and it reads in a query.
-- ----------------------------------------------------------------------------
IF OBJECT_ID('dbo.geo_origin', 'U') IS NULL
CREATE TABLE dbo.geo_origin (
  slug       NVARCHAR(100) NOT NULL PRIMARY KEY,
  name       NVARCHAR(400) NOT NULL,

  -- Degrees, WGS84. Real numbers, not text: a coordinate is arithmetic, not a
  -- code.
  latitude   FLOAT NOT NULL,
  longitude  FLOAT NOT NULL,

  is_default BIT NOT NULL DEFAULT 0,

  created_at NVARCHAR(30) NOT NULL DEFAULT (CONVERT(varchar(19), GETUTCDATE(), 126))
);
GO

-- The same rule as `organization`: at most one origin may claim is_default.
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'geo_origin_one_default' AND object_id = OBJECT_ID('dbo.geo_origin'))
  CREATE UNIQUE INDEX geo_origin_one_default ON dbo.geo_origin (is_default) WHERE is_default = 1;
GO


-- ----------------------------------------------------------------------------
--  vendor_site_geo — where a vendor site is, and how far it is from an origin.
--
--  ★★ `geocode_status` HAS NO CHECK, AND THAT IS CARRIED ACROSS DELIBERATELY.
--     The source file explains: SQLite cannot relax a CHECK without rebuilding
--     the table, and a fifth status is a likelier future edit than a wrong
--     `permanent` flag. T-SQL *can* relax a CHECK, so the reason is weaker here —
--     but the constraint is still omitted, because adding one would make the two
--     schemas differ on a column whose set of values is expected to grow.
--
--  ★★ `NULL` IS NOT ZERO, ON EVERY NUMERIC COLUMN HERE. An unroutable pair
--     returns no distance, and writing 0 would assert that the site sits at the
--     origin -- a real and meaningful value, and one that would then be
--     indistinguishable from "no route".
-- ----------------------------------------------------------------------------
IF OBJECT_ID('dbo.vendor_site_geo', 'U') IS NULL
CREATE TABLE dbo.vendor_site_geo (
  vendor_site_id   INT NOT NULL PRIMARY KEY,

  latitude         FLOAT NULL,
  longitude        FLOAT NULL,

  geocode_status   NVARCHAR(30) NOT NULL,
  geocode_reason   NVARCHAR(MAX) NULL,

  match_confidence NVARCHAR(20) NULL,
  accuracy         NVARCHAR(30) NULL,
  feature_type     NVARCHAR(50) NULL,

  -- ★★ 600, NOT 200, AND THE NUMBER IS MEASURED. The Mapbox id is a base64-ish
  --    `mapbox://` URI whose length depends on the feature, and the observed
  --    maximum across the 800 stored pins is 503 characters. At NVARCHAR(200) the
  --    bulk load failed with error 2628 ("String or binary data would be
  --    truncated"), which names the column and the truncated prefix.
  --
  --    ★ THE SOURCE FILE'S `TEXT` HAS NO LENGTH, WHICH IS WHY THIS WAS EASY TO GET
  --      WRONG. SQLite's TEXT is unbounded, so a translation has to CHOOSE a width
  --      -- and 200 was chosen from the column's apparent purpose rather than from
  --      the data. The measurement is what corrected it.
  mapbox_id        NVARCHAR(600) NULL,
  query_address    NVARCHAR(MAX) NULL,
  address_hash     NVARCHAR(100) NULL,

  -- The licence, on the row. The geocoder permits STORING a result only when the
  -- request carried `permanent=true`, so it is recorded per row rather than
  -- trusted to code somebody might edit later.
  permanent        BIT NOT NULL DEFAULT 0,

  geocoded_at      NVARCHAR(30) NOT NULL DEFAULT (CONVERT(varchar(19), GETUTCDATE(), 126)),

  drive_miles       FLOAT NULL,
  drive_minutes     FLOAT NULL,
  drive_status      NVARCHAR(30) NULL,

  -- ★ NOT A FOREIGN KEY, DELIBERATELY. This is the PROVENANCE of a measurement,
  --   and provenance has to outlive the thing it names -- deleting an origin must
  --   not delete or detach the record of what was measured from it.
  drive_origin_slug NVARCHAR(100) NULL,
  drive_at          NVARCHAR(30) NULL
);
GO


-- ----------------------------------------------------------------------------
--  vendor_site_route — the road between the origin and a pin, and its turns.
--
--  ★★ `route_miles` IS NOT `drive_miles`, AND THE SOURCE FILE MEASURES THE GAP.
--     They come from two different Mapbox services and genuinely disagree --
--     11 of 24 sites agree within a mile, worst gap 34.48 mi. Both are kept, both
--     are named where shown, and neither stands in for the other.
--
--  ★ `route_status` IS NOT NULL, because the only way to have no answer is to have
--    no row. A NULL would be a fourth state meaning the same as absence.
-- ----------------------------------------------------------------------------
IF OBJECT_ID('dbo.vendor_site_route', 'U') IS NULL
CREATE TABLE dbo.vendor_site_route (
  vendor_site_id    INT NOT NULL PRIMARY KEY,

  route_status      NVARCHAR(30) NOT NULL,
  route_reason      NVARCHAR(MAX) NULL,

  route_miles       FLOAT NULL,
  route_minutes     FLOAT NULL,

  route_origin_slug NVARCHAR(100) NULL,

  -- A hash of the pin AND the origin AND the derivation version. See the source
  -- file: the first live run stored route_miles in METRES while writing a
  -- perfectly correct pin_hash, so a hash over the inputs alone could not tell
  -- "current" from "written by a version of the script that was wrong".
  pin_hash          NVARCHAR(100) NULL,

  -- A JSON array of [longitude, latitude] pairs at 5 decimal places -- the plain
  -- LineString coordinate list, not a GeoJSON document.
  geometry          NVARCHAR(MAX) NULL,

  -- A JSON array of the turns, in order. The steps sum to route_miles exactly
  -- (verified on six routes, delta 0.000 mi on all six), which is what makes it
  -- legitimate to print both a step's length and a route total.
  steps             NVARCHAR(MAX) NULL,
  step_count        INT NULL,

  route_at          NVARCHAR(30) NOT NULL DEFAULT (CONVERT(varchar(19), GETUTCDATE(), 126))
);
GO


-- ----------------------------------------------------------------------------
--  field_override — a name of our own for a value the ledger already holds.
--
--  ★ THE PRIMARY KEY IS THE NATURAL TRIPLE, NOT A SURROGATE ID. The uniqueness
--    the app needs is "one value per field of one subject", and a surrogate id
--    would permit two.
--
--  ★ NO FOREIGN KEY: neither half of the key lives in this database. `subject_key`
--    names a row in the LEDGER.
-- ----------------------------------------------------------------------------
IF OBJECT_ID('dbo.field_override', 'U') IS NULL
CREATE TABLE dbo.field_override (
  subject_kind    NVARCHAR(50) NOT NULL,
  subject_key     NVARCHAR(400) NOT NULL,
  subject_written NVARCHAR(400) NULL,
  field           NVARCHAR(100) NOT NULL,
  value           NVARCHAR(MAX) NOT NULL,
  set_by          NVARCHAR(200) NOT NULL,
  set_at          NVARCHAR(30) NOT NULL DEFAULT (CONVERT(varchar(19), GETUTCDATE(), 126)),

  CONSTRAINT PK_field_override PRIMARY KEY (subject_kind, subject_key, field)
);
GO


-- ----------------------------------------------------------------------------
--  ledger_read_cap — how many rows this app reads from a ledger object, and in
--  what order.
--
--  ★★ `order_by` IS REQUIRED WHENEVER `max_rows` IS SET, AND THE ROUTE ENFORCES
--     IT RATHER THAN THE SCHEMA. A cap with no ordering is not a smaller answer --
--     it is a DIFFERENT, ARBITRARY one, and the un-ordered form is the one that
--     arrives looking correct. The refusal lives in `routes/readCaps.ts` because
--     it needs to name what is wrong, which a CHECK constraint cannot do.
-- ----------------------------------------------------------------------------
IF OBJECT_ID('dbo.ledger_read_cap', 'U') IS NULL
CREATE TABLE dbo.ledger_read_cap (
  table_name  NVARCHAR(200) NOT NULL PRIMARY KEY,
  sql         NVARCHAR(MAX) NULL,
  max_rows    INT NULL,
  order_by    NVARCHAR(400) NULL,
  note        NVARCHAR(MAX) NULL,
  set_by      NVARCHAR(200) NULL,
  set_at      NVARCHAR(30) NOT NULL DEFAULT (CONVERT(varchar(19), GETUTCDATE(), 126))
);
GO


-- ----------------------------------------------------------------------------
--  table_count_snapshot — one row count per object per day.
--
--  ★ `counted_in` IS THE DIFFERENCE BETWEEN A FIGURE AND A CLAIM. The register's
--    counts come from whichever store actually holds the object, and the two are
--    different databases with different numbers. Without this column a reading is
--    a bare integer the page has to ASSUME came from the store the current
--    configuration names -- an assumption that was already false once.
--
--  ★ A reading with no `counted_in` is one this register will NOT serve, because
--    it cannot say what it counted. NULL is meaningful and is not "assume current".
-- ----------------------------------------------------------------------------
IF OBJECT_ID('dbo.table_count_snapshot', 'U') IS NULL
CREATE TABLE dbo.table_count_snapshot (
  id            INT IDENTITY(1,1) NOT NULL PRIMARY KEY,

  object_name   NVARCHAR(200) NOT NULL,

  -- The day the reading belongs to, `YYYY-MM-DD`, in the app's own local clock.
  snapshot_date NVARCHAR(10) NOT NULL,

  row_count     INT NOT NULL,

  counted_in    NVARCHAR(20) NULL,

  captured_at   NVARCHAR(30) NOT NULL DEFAULT (CONVERT(varchar(19), GETUTCDATE(), 126)),

  CONSTRAINT UQ_table_count_snapshot UNIQUE (object_name, snapshot_date)
);
GO
