-- ============================================================================
--  Turso sample schema — a SURROGATE for Oracle EBS 12.2, not a replica.
--
--  Dialect: SQLite / libSQL (Turso).  NOT runnable on Oracle.
--  Seeds:   see 02-seed.sql (generated by scripts/build-turso-sample.mjs).
--
--  ---------------------------------------------------------------------------
--  READ THIS BEFORE TRUSTING ANY NUMBER THAT COMES OUT OF HERE
--  ---------------------------------------------------------------------------
--  This reproduces the SHAPE and SEMANTICS of the standard EBS objects — column
--  names, the ACTUAL_FLAG discriminator, the seven segments, the join keys — but
--  not Oracle's internals.  Specifically it does NOT reproduce:
--
--    * Oracle NUMBER precision or its round-half-up rule. Money is REAL here.
--      (Measured, not assumed: every figure in the report reconciles exactly at
--      these magnitudes. See 03-notes.sql, "Why REAL is safe enough".)
--    * Oracle's rule that '' IS NULL.  In SQLite '' and NULL are DIFFERENT.
--      Every text column must therefore be normalized on load, not at query time.
--    * CHAR blank-padding, NLS sort order, the optimizer, or any index behaviour.
--      A query that is correct here is NOT thereby fast on Oracle.
--
--  Object naming
--    Standard EBS objects carry their real Oracle names (GL_BALANCES, ...) so the
--    SQL in data/sql/00..04 can be ported with minimal edits.
--    EBS's "APPS.X is a synonym for X.X#" shadow-table convention is a synonym
--    mechanism, not a data difference, so there is no separate shadow table — the
--    names here are the canonical ones and `APPS.` / `GL.` prefixes are dropped.
--
--  Row provenance
--    Every seeded row carries DATA_ORIGIN via SAMPLE_DATA_PROVENANCE:
--      'extract'     — copied verbatim from data/oracle/*.json
--      'derived'     — computed from extract values, not invented
--      'transcribed' — read off the report image (report-findings.md section 2)
--      'synthetic'   — authored to make a query reproducible; nothing else worked
-- ============================================================================


-- ============================================================================
--  0. Provenance — so "what in here is real?" is one query, not a guess.
-- ============================================================================

CREATE TABLE IF NOT EXISTS SAMPLE_DATA_PROVENANCE (
  TABLE_NAME   TEXT    NOT NULL,
  ROW_KEY      TEXT    NOT NULL,
  DATA_ORIGIN  TEXT    NOT NULL
                CHECK (DATA_ORIGIN IN ('extract','derived','transcribed','synthetic')),
  SOURCE_FILE  TEXT,
  NOTE         TEXT,
  PRIMARY KEY (TABLE_NAME, ROW_KEY)
);

-- Oracle's DUAL. A single-row no-column table. Also carries SYSDATE, which is
-- what makes `SELECT SYSDATE FROM DUAL` work — there is no sysdate() function.
CREATE VIEW IF NOT EXISTS DUAL AS
  SELECT 'X' AS DUMMY, datetime('now') AS SYSDATE;


-- ============================================================================
--  1. General Ledger
-- ============================================================================

-- GL_LEDGERS. The chart of accounts and the currency live here, which is what
-- lets a query derive the currency instead of hard-coding it.
CREATE TABLE IF NOT EXISTS GL_LEDGERS (
  LEDGER_ID            INTEGER PRIMARY KEY,
  NAME                 TEXT    NOT NULL,
  SHORT_NAME           TEXT,
  CHART_OF_ACCOUNTS_ID INTEGER NOT NULL,
  CURRENCY_CODE        TEXT    NOT NULL,
  PERIOD_SET_NAME      TEXT    NOT NULL,
  LEDGER_CATEGORY_CODE TEXT,
  DESCRIPTION          TEXT
);

-- FND_CURRENCIES. Needed because gl_balances.currency_code must be checkable
-- against a real currency, not free text.
CREATE TABLE IF NOT EXISTS FND_CURRENCIES (
  CURRENCY_CODE      TEXT PRIMARY KEY,
  NAME               TEXT NOT NULL,
  PRECISION          INTEGER,
  EXTENDED_PRECISION INTEGER,
  ENABLED_FLAG       TEXT DEFAULT 'Y'
);

-- GL_PERIODS. PERIOD_NAME is a string like 'JUL-25' and sorts WRONG as text,
-- which is why PERIOD_YEAR and PERIOD_NUM exist and why everything orders by
-- them instead. That trap is inherited from Oracle, deliberately.
CREATE TABLE IF NOT EXISTS GL_PERIODS (
  PERIOD_SET_NAME TEXT    NOT NULL,
  PERIOD_NAME     TEXT    NOT NULL,
  PERIOD_TYPE     TEXT    NOT NULL DEFAULT 'Month',
  PERIOD_YEAR     INTEGER NOT NULL,
  PERIOD_NUM      INTEGER NOT NULL,
  QUARTER_NUM     INTEGER,
  START_DATE      TEXT    NOT NULL,   -- 'YYYY-MM-DD'
  END_DATE        TEXT    NOT NULL,
  PRIMARY KEY (PERIOD_SET_NAME, PERIOD_NAME)
);

-- FND_ID_FLEX_STRUCTURES + FND_ID_FLEX_SEGMENTS. The chart of accounts is a
-- key flexfield; these describe its seven segments and their order.
CREATE TABLE IF NOT EXISTS FND_ID_FLEX_STRUCTURES (
  ID_FLEX_NUM              INTEGER PRIMARY KEY,
  ID_FLEX_STRUCTURE_CODE   TEXT NOT NULL,
  ID_FLEX_CODE             TEXT NOT NULL,
  DESCRIPTION              TEXT
);

CREATE TABLE IF NOT EXISTS FND_ID_FLEX_SEGMENTS (
  ID_FLEX_NUM          INTEGER NOT NULL,
  ID_FLEX_CODE         TEXT    NOT NULL,
  SEGMENT_NUM          INTEGER NOT NULL,
  SEGMENT_NAME         TEXT    NOT NULL,
  APPLICATION_COLUMN   TEXT    NOT NULL,
  FLEX_VALUE_SET_ID    INTEGER,
  DISPLAY_SIZE         INTEGER,
  REQUIRED_FLAG        TEXT,
  ENABLED_FLAG         TEXT,
  PRIMARY KEY (ID_FLEX_NUM, SEGMENT_NUM)
);

-- FND_FLEX_VALUES. The per-segment value legend, which is how a bare code like
-- '0450' becomes "Athens Drive HS". Only populated where a name is known; a
-- value present with no row here is UNNAMED, and that is a real state, not a bug.
CREATE TABLE IF NOT EXISTS FND_FLEX_VALUES (
  FLEX_VALUE_SET_ID  INTEGER NOT NULL,
  FLEX_VALUE         TEXT    NOT NULL,
  DESCRIPTION        TEXT,
  ENABLED_FLAG       TEXT DEFAULT 'Y',
  SUMMARY_FLAG       TEXT DEFAULT 'N',
  START_DATE_ACTIVE  TEXT,
  END_DATE_ACTIVE    TEXT,
  PRIMARY KEY (FLEX_VALUE_SET_ID, FLEX_VALUE)
);

CREATE TABLE IF NOT EXISTS FND_FLEX_VALUES_TL (
  FLEX_VALUE_SET_ID INTEGER NOT NULL,
  FLEX_VALUE        TEXT    NOT NULL,
  LANGUAGE          TEXT    NOT NULL DEFAULT 'US',
  DESCRIPTION       TEXT,
  PRIMARY KEY (FLEX_VALUE_SET_ID, FLEX_VALUE, LANGUAGE)
);

-- GL_CODE_COMBINATIONS. The account combinations.
--
-- SEGMENT5 is the project identifier and SEGMENT2 is the Capital/Operating axis
-- ('6570' Capital, '9000' Operating, '6560' Relocation) — inferred, see
-- report-findings.md section 6 and data/sql/00-discover.sql section H.
--
-- WARNING: CODE_COMBINATION_ID is a surrogate key and is NOT durable. A chart-of-
-- accounts reimplementation, a COA copy into a new ledger, or a rebuild of this
-- table all reassign it. Join on SEGMENT1..7 across any boundary you do not
-- control — especially the extract boundary.
CREATE TABLE IF NOT EXISTS GL_CODE_COMBINATIONS (
  CODE_COMBINATION_ID INTEGER PRIMARY KEY,
  CHART_OF_ACCOUNTS_ID INTEGER NOT NULL,
  ACCOUNT_TYPE        TEXT    NOT NULL,   -- 'A' asset 'L' liab 'O' owner 'R' rev 'E' expense
  ENABLED_FLAG        TEXT    NOT NULL DEFAULT 'Y',
  SUMMARY_FLAG        TEXT    NOT NULL DEFAULT 'N',  -- 'Y' = parent, must be EXCLUDED from sums
  SEGMENT1            TEXT    NOT NULL,   -- Fund
  SEGMENT2            TEXT    NOT NULL,   -- Purpose
  SEGMENT3            TEXT    NOT NULL,   -- Program
  SEGMENT4            TEXT    NOT NULL,   -- Object
  SEGMENT5            TEXT    NOT NULL,   -- Level  (the project)
  SEGMENT6            TEXT    NOT NULL,   -- Cost Center
  SEGMENT7            TEXT    NOT NULL,   -- Future use
  DESCRIPTION         TEXT,
  LAST_UPDATE_DATE    TEXT,
  CREATION_DATE       TEXT,
  FOREIGN KEY (CHART_OF_ACCOUNTS_ID) REFERENCES FND_ID_FLEX_STRUCTURES (ID_FLEX_NUM)
);

-- The canonical join key for this codebase: the seven segments, not the CCID.
CREATE VIEW IF NOT EXISTS V_CODE_COMBINATION_KEY AS
  SELECT CODE_COMBINATION_ID, CHART_OF_ACCOUNTS_ID, ACCOUNT_TYPE,
         ENABLED_FLAG, SUMMARY_FLAG,
         SEGMENT1||'.'||SEGMENT2||'.'||SEGMENT3||'.'||SEGMENT4||'.'||
         SEGMENT5||'.'||SEGMENT6||'.'||SEGMENT7 AS COMBINATION_KEY
    FROM GL_CODE_COMBINATIONS;

-- GL_BALANCES. THE table for this whole exercise.
--
-- Oracle keeps BUDGET, ENCUMBRANCE and ACTUAL in this one table, discriminated
-- by ACTUAL_FLAG:
--     'B' = Budget      'E' = Encumbrance      'A' = Actual
-- So "does Oracle hold a budget?" is literally "are there ACTUAL_FLAG='B' rows?".
--
-- There are FIVE filters that are NOT optional when summing budget. Drop any one
-- and the total silently inflates, because the table legitimately contains the
-- rows you are then counting. The seed deliberately includes rows that only the
-- filters exclude, so a query missing a filter returns a visibly WRONG number
-- here rather than a plausible one:
--     LEDGER_ID              rows for other ledgers
--     TRANSLATED_FLAG='N'    the same balances restated into a reporting currency
--     CURRENCY_CODE          the restated rows carry a different currency
--     ENCUMBRANCE_TYPE_ID IS NULL  encumbrance rows carry an id, budget rows do not
--     ACTUAL_FLAG='B'        actuals and encumbrances share the table
CREATE TABLE IF NOT EXISTS GL_BALANCES (
  LEDGER_ID            INTEGER NOT NULL,
  CODE_COMBINATION_ID  INTEGER NOT NULL,
  PERIOD_NAME          TEXT    NOT NULL,   -- 'JUL-25' — sorts wrong as text
  PERIOD_YEAR          INTEGER NOT NULL,   -- real number, sorts right
  PERIOD_NUM           INTEGER NOT NULL,   -- 1..12, real number, sorts right
  PERIOD_TYPE          TEXT    NOT NULL DEFAULT 'Month',
  ACTUAL_FLAG          TEXT    NOT NULL CHECK (ACTUAL_FLAG IN ('A','B','E')),
  BUDGET_VERSION_ID    INTEGER,            -- NULL for 'A' and 'E'
  ENCUMBRANCE_TYPE_ID  INTEGER,            -- NULL for 'A' and 'B'
  CURRENCY_CODE        TEXT    NOT NULL,
  TRANSLATED_FLAG      TEXT    NOT NULL DEFAULT 'N' CHECK (TRANSLATED_FLAG IN ('Y','N')),
  PERIOD_NET_DR        REAL    NOT NULL DEFAULT 0,
  PERIOD_NET_CR        REAL    NOT NULL DEFAULT 0,
  BEGIN_BALANCE_DR     REAL    NOT NULL DEFAULT 0,
  BEGIN_BALANCE_CR     REAL    NOT NULL DEFAULT 0,
  QUARTER_TO_DATE_DR   REAL    NOT NULL DEFAULT 0,
  QUARTER_TO_DATE_CR   REAL    NOT NULL DEFAULT 0,
  FOREIGN KEY (LEDGER_ID)           REFERENCES GL_LEDGERS (LEDGER_ID),
  FOREIGN KEY (CODE_COMBINATION_ID) REFERENCES GL_CODE_COMBINATIONS (CODE_COMBINATION_ID)
);

-- The composite key from the schema doc. NULLs are normalized to sentinels
-- because SQLite treats NULLs as distinct in a unique index, which would silently
-- permit duplicate rows.
CREATE UNIQUE INDEX IF NOT EXISTS UX_GL_BALANCES_K1 ON GL_BALANCES (
  LEDGER_ID, CODE_COMBINATION_ID, PERIOD_NAME, ACTUAL_FLAG,
  IFNULL(BUDGET_VERSION_ID, -1), IFNULL(ENCUMBRANCE_TYPE_ID, -1), CURRENCY_CODE, TRANSLATED_FLAG
);
CREATE INDEX IF NOT EXISTS IX_GL_BALANCES_ACCT  ON GL_BALANCES (CODE_COMBINATION_ID, ACTUAL_FLAG);
CREATE INDEX IF NOT EXISTS IX_GL_BALANCES_PERIOD ON GL_BALANCES (PERIOD_YEAR, PERIOD_NUM);

-- GL_BUDGET_TYPES. The kind of budget (Appropriation, Grant, Project, ...).
CREATE TABLE IF NOT EXISTS GL_BUDGET_TYPES (
  BUDGET_TYPE_ID   INTEGER PRIMARY KEY,
  BUDGET_TYPE_CODE TEXT NOT NULL UNIQUE,
  BUDGET_NAME      TEXT NOT NULL,
  DESCRIPTION      TEXT,
  ENABLED_FLAG     TEXT DEFAULT 'Y'
);

-- GL_BUDGET_VERSIONS. Which version of a budget applies, and over which period
-- range. FIRST_PERIOD_NAME / LAST_PERIOD_NAME define the version's span.
--
-- NOTE the grain inversion that matters for "when was this first funded?":
-- a budget version spans a BUDGET TYPE; funding is per CODE COMBINATION. The
-- version's first period is NOT necessarily the code's first funded period.
CREATE TABLE IF NOT EXISTS GL_BUDGET_VERSIONS (
  BUDGET_VERSION_ID  INTEGER PRIMARY KEY,
  LEDGER_ID          INTEGER NOT NULL,
  BUDGET_TYPE_ID     INTEGER NOT NULL,
  BUDGET_NAME        TEXT    NOT NULL,
  FIRST_PERIOD_NAME  TEXT,
  LAST_PERIOD_NAME   TEXT,
  DEFAULT_PERIOD_NAME TEXT,
  STATUS_CODE        TEXT,               -- 'OPEN' / 'CURRENT' / 'FROZEN'
  LATEST_FLAG        TEXT DEFAULT 'N',   -- 'Y' on exactly one version per budget type
  BUDGET_ENTRY_STATUS TEXT,
  CREATION_DATE      TEXT,
  FOREIGN KEY (LEDGER_ID)      REFERENCES GL_LEDGERS (LEDGER_ID),
  FOREIGN KEY (BUDGET_TYPE_ID) REFERENCES GL_BUDGET_TYPES (BUDGET_TYPE_ID)
);

-- GL_BUDGET_ENTITIES. What a budget is kept against.
CREATE TABLE IF NOT EXISTS GL_BUDGET_ENTITIES (
  BUDGET_ENTITY_ID   INTEGER PRIMARY KEY,
  BUDGET_TYPE_ID     INTEGER NOT NULL,
  BUDGET_ENTITY_NAME TEXT    NOT NULL,
  ENABLED_FLAG       TEXT DEFAULT 'Y',
  FOREIGN KEY (BUDGET_TYPE_ID) REFERENCES GL_BUDGET_TYPES (BUDGET_TYPE_ID)
);

-- GL_BUDGET_ASSIGNMENTS. Which accounts a version covers.
-- IMPORTANT: this holds account RANGES, not a per-account list. RANGE_FROM and
-- RANGE_TO are concatenated segment strings, compared against however EBS joins
-- the segments for the chart of accounts. Retrieve the rows and test membership;
-- do not assume a plain BETWEEN matches EBS's concatenation.
CREATE TABLE IF NOT EXISTS GL_BUDGET_ASSIGNMENTS (
  BUDGET_VERSION_ID  INTEGER NOT NULL,
  RANGE_FROM         TEXT,
  RANGE_TO           TEXT,
  BUDGET_ENTITY_ID   INTEGER,
  PRIMARY KEY (BUDGET_VERSION_ID, RANGE_FROM, RANGE_TO),
  FOREIGN KEY (BUDGET_VERSION_ID) REFERENCES GL_BUDGET_VERSIONS (BUDGET_VERSION_ID)
);

-- GL_JE_HEADERS / GL_JE_LINES. The journal, and the authoritative answer to
-- "when was this funded?" — GL_BALANCES is a per-period rollup and loses the
-- action date; the journal keeps it in DEFAULT_EFFECTIVE_DATE.
CREATE TABLE IF NOT EXISTS GL_JE_HEADERS (
  JE_HEADER_ID           INTEGER PRIMARY KEY,
  LEDGER_ID              INTEGER NOT NULL,
  JE_CATEGORY            TEXT    NOT NULL,   -- 'Budget' / 'Purchase' / 'Adjustment'
  JE_SOURCE              TEXT    NOT NULL,
  PERIOD_NAME            TEXT    NOT NULL,
  NAME                   TEXT,
  STATUS                 TEXT,               -- 'U' unposted / 'P' posted
  DATE_CREATED           TEXT,
  ACTUAL_FLAG            TEXT    NOT NULL DEFAULT 'A',
  DEFAULT_EFFECTIVE_DATE TEXT,               -- the action date; the BOE date
  ENCUMBRANCE_TYPE_ID    INTEGER,
  POSTED_DATE            TEXT,
  DESCRIPTION            TEXT,
  FOREIGN KEY (LEDGER_ID) REFERENCES GL_LEDGERS (LEDGER_ID)
);

CREATE TABLE IF NOT EXISTS GL_JE_LINES (
  JE_HEADER_ID        INTEGER NOT NULL,
  JE_LINE_NUM         INTEGER NOT NULL,
  LEDGER_ID           INTEGER NOT NULL,
  EFFECTIVE_DATE      TEXT,
  CODE_COMBINATION_ID INTEGER NOT NULL,
  STATUS              TEXT,
  ENTERED_DR          REAL NOT NULL DEFAULT 0,
  ENTERED_CR          REAL NOT NULL DEFAULT 0,
  DESCRIPTION         TEXT,
  LINE_TYPE_CODE      TEXT,
  INVOICE_IDENTIFIER  TEXT,
  INVOICE_AMOUNT      REAL,
  PRIMARY KEY (JE_HEADER_ID, JE_LINE_NUM),
  FOREIGN KEY (JE_HEADER_ID)        REFERENCES GL_JE_HEADERS (JE_HEADER_ID),
  FOREIGN KEY (CODE_COMBINATION_ID) REFERENCES GL_CODE_COMBINATIONS (CODE_COMBINATION_ID)
);

-- GL_LOOKUPS. Decode values ('YES_NO', 'BUDGET_STATUS', ...).
CREATE TABLE IF NOT EXISTS GL_LOOKUPS (
  LOOKUP_TYPE   TEXT NOT NULL,
  LOOKUP_CODE   TEXT NOT NULL,
  MEANING       TEXT,
  DESCRIPTION   TEXT,
  ENABLED_FLAG  TEXT DEFAULT 'Y',
  PRIMARY KEY (LOOKUP_TYPE, LOOKUP_CODE)
);


-- ============================================================================
--  2. Purchasing
-- ============================================================================

CREATE TABLE IF NOT EXISTS PO_VENDORS (
  VENDOR_ID               INTEGER PRIMARY KEY,
  VENDOR_NAME             TEXT NOT NULL,
  VENDOR_TYPE_LOOKUP_CODE TEXT,
  CUSTOMER_NUM            TEXT,
  PARENT_VENDOR_ID        INTEGER,
  ENABLED_FLAG            TEXT DEFAULT 'Y',
  CREATION_DATE           TEXT
);

CREATE TABLE IF NOT EXISTS PO_VENDOR_SITES_ALL (
  VENDOR_SITE_ID      INTEGER PRIMARY KEY,
  VENDOR_ID           INTEGER NOT NULL,
  VENDOR_SITE_CODE    TEXT,
  ADDRESS_LINE1       TEXT,
  ADDRESS_LINE2       TEXT,
  ADDRESS_LINE3       TEXT,
  CITY                TEXT,
  STATE               TEXT,
  ZIP                 TEXT,
  AREA_CODE           TEXT,
  PHONE               TEXT,
  CUSTOMER_NUM        TEXT,
  ORG_ID              INTEGER,
  FOREIGN KEY (VENDOR_ID) REFERENCES PO_VENDORS (VENDOR_ID)
);

-- PO_AGENTS. The buyer.
CREATE TABLE IF NOT EXISTS PO_AGENTS (
  AGENT_ID    INTEGER PRIMARY KEY,
  NAME        TEXT NOT NULL,
  AUTHORIZATION_LIMIT REAL,
  ENABLED_FLAG TEXT DEFAULT 'Y'
);

CREATE TABLE IF NOT EXISTS PO_LINE_TYPES (
  LINE_TYPE_ID    INTEGER PRIMARY KEY,
  LINE_TYPE       TEXT,
  DESCRIPTION     TEXT,
  PURCHASE_BASIS  TEXT,
  MATCHING_BASIS  TEXT,
  ORDER_TYPE_LOOKUP_CODE TEXT
);

CREATE TABLE IF NOT EXISTS PO_HEADERS_ALL (
  PO_HEADER_ID     INTEGER PRIMARY KEY,
  PO_NUMBER        TEXT,
  TYPE_LOOKUP_CODE TEXT,
  VENDOR_ID        INTEGER,
  VENDOR_SITE_ID   INTEGER,
  AGENT_ID         INTEGER,
  APPROVED_FLAG    TEXT,
  APPROVED_DATE    TEXT,
  START_DATE_ACTIVE TEXT,
  ORG_ID           INTEGER,
  CANCEL_FLAG      TEXT DEFAULT 'N',
  EXP_PROJECT_NAME TEXT,
  EXP_PO_NUMBER    TEXT,
  FOREIGN KEY (VENDOR_ID) REFERENCES PO_VENDORS (VENDOR_ID),
  FOREIGN KEY (AGENT_ID)  REFERENCES PO_AGENTS (AGENT_ID)
);

CREATE TABLE IF NOT EXISTS PO_LINES_ALL (
  PO_LINE_ID       INTEGER PRIMARY KEY,
  PO_HEADER_ID     INTEGER NOT NULL,
  LINE_TYPE_ID     INTEGER,
  LINE_NUM         INTEGER NOT NULL,
  ITEM_ID          INTEGER,
  ITEM_DESCRIPTION TEXT,
  UNIT_MEAS_LOOKUP_CODE TEXT,
  UNIT_PRICE       REAL,
  QUANTITY         REAL,
  CLOSED_CODE      TEXT,
  CANCEL_FLAG      TEXT DEFAULT 'N',
  FOREIGN KEY (PO_HEADER_ID) REFERENCES PO_HEADERS_ALL (PO_HEADER_ID)
);

CREATE TABLE IF NOT EXISTS PO_LINE_LOCATIONS_ALL (
  LINE_LOCATION_ID  INTEGER PRIMARY KEY,
  PO_HEADER_ID      INTEGER NOT NULL,
  PO_LINE_ID        INTEGER NOT NULL,
  SHIPMENT_NUM      INTEGER DEFAULT 1,
  SHIP_TO_LOCATION_ID INTEGER,
  QUANTITY          REAL,
  QUANTITY_RECEIVED REAL,
  AMOUNT_RECEIVED   REAL,
  UNIT_MEAS_LOOKUP_CODE TEXT,
  PO_RELEASE_ID     INTEGER,
  APPROVED_FLAG     TEXT,
  CLOSED_CODE       TEXT,
  FOREIGN KEY (PO_HEADER_ID) REFERENCES PO_HEADERS_ALL (PO_HEADER_ID),
  FOREIGN KEY (PO_LINE_ID)   REFERENCES PO_LINES_ALL (PO_LINE_ID)
);

-- PO_DISTRIBUTIONS_ALL. Where the money is actually charged — this is the row
-- that carries CODE_COMBINATION_ID and therefore the link to the account.
CREATE TABLE IF NOT EXISTS PO_DISTRIBUTIONS_ALL (
  PO_DISTRIBUTION_ID      INTEGER PRIMARY KEY,
  PO_HEADER_ID            INTEGER NOT NULL,
  PO_LINE_ID              INTEGER NOT NULL,
  LINE_LOCATION_ID        INTEGER,
  CODE_COMBINATION_ID     INTEGER NOT NULL,
  DELIVER_TO_LOCATION_ID  INTEGER,
  DISTRIBUTION_NUM        INTEGER DEFAULT 1,
  QUANTITY_ORDERED        REAL,
  AMOUNT_ORDERED          REAL,
  AMOUNT_BILLED           REAL,
  ENCUMBERED_FLAG         TEXT,
  ENCUMBERED_AMOUNT       REAL,
  FOREIGN KEY (PO_HEADER_ID)        REFERENCES PO_HEADERS_ALL (PO_HEADER_ID),
  FOREIGN KEY (PO_LINE_ID)          REFERENCES PO_LINES_ALL (PO_LINE_ID),
  FOREIGN KEY (CODE_COMBINATION_ID) REFERENCES GL_CODE_COMBINATIONS (CODE_COMBINATION_ID)
);

CREATE TABLE IF NOT EXISTS PO_LOOKUP_CODES (
  LOOKUP_TYPE  TEXT NOT NULL,
  LOOKUP_CODE  TEXT NOT NULL,
  DESCRIPTION  TEXT,
  PRIMARY KEY (LOOKUP_TYPE, LOOKUP_CODE)
);


-- ============================================================================
--  3. Payables
-- ============================================================================

CREATE TABLE IF NOT EXISTS AP_INVOICES_ALL (
  INVOICE_ID         INTEGER PRIMARY KEY,
  INVOICE_NUM        TEXT,
  VENDOR_ID          INTEGER,
  VENDOR_SITE_ID     INTEGER,
  INVOICE_AMOUNT     REAL,
  AMOUNT_PAID        REAL DEFAULT 0,
  INVOICE_DATE       TEXT,
  DESCRIPTION        TEXT,
  TAX_AMOUNT         REAL DEFAULT 0,
  PAYMENT_STATUS_FLAG TEXT,
  PO_HEADER_ID       INTEGER,
  FOREIGN KEY (VENDOR_ID)     REFERENCES PO_VENDORS (VENDOR_ID),
  FOREIGN KEY (PO_HEADER_ID)  REFERENCES PO_HEADERS_ALL (PO_HEADER_ID)
);

CREATE TABLE IF NOT EXISTS AP_INV_LINES (
  LINE_NUMBER          INTEGER NOT NULL,
  INVOICE_ID           INTEGER NOT NULL,
  LINE_TYPE_LOOKUP_CODE TEXT,
  MATCH_TYPE           TEXT,
  AMOUNT               REAL,
  PRIMARY KEY (INVOICE_ID, LINE_NUMBER),
  FOREIGN KEY (INVOICE_ID) REFERENCES AP_INVOICES_ALL (INVOICE_ID)
);

CREATE TABLE IF NOT EXISTS AP_INVOICE_DISTRIBUTIONS_ALL (
  INVOICE_DISTRIBUTION_ID INTEGER PRIMARY KEY,
  INVOICE_ID              INTEGER NOT NULL,
  INVOICE_LINE_NUMBER     INTEGER,
  PO_DISTRIBUTION_ID      INTEGER,
  CODE_COMBINATION_ID     INTEGER NOT NULL,
  DISTRIBUTION_LINE_NUMBER INTEGER,
  AMOUNT                  REAL,
  ACCOUNTING_DATE         TEXT,
  FOREIGN KEY (INVOICE_ID)          REFERENCES AP_INVOICES_ALL (INVOICE_ID),
  FOREIGN KEY (CODE_COMBINATION_ID) REFERENCES GL_CODE_COMBINATIONS (CODE_COMBINATION_ID)
);

CREATE TABLE IF NOT EXISTS AP_INVOICE_PAYMENTS_ALL (
  INVOICE_PAYMENT_ID INTEGER PRIMARY KEY,
  INVOICE_ID         INTEGER NOT NULL,
  AMOUNT             REAL,
  PAYMENT_DATE       TEXT,
  CHECK_NUMBER       TEXT,
  FOREIGN KEY (INVOICE_ID) REFERENCES AP_INVOICES_ALL (INVOICE_ID)
);


-- ============================================================================
--  4. Projects — the secondary reading of the report.
--     report-findings.md section 1 says the report's *Project master* layer may
--     resolve here rather than in GL.
--
--     SOURCE CONFIRMED, AND IT IS EMPTY. `POWERAPPS` holds SELECT on
--     PA_PROJECTS_ALL#, PA_TASKS#, PA_BUDGET_VERSIONS# and PA_BUDGET_LINES#,
--     resolved through APPS-owned synonyms, so these are readable on the live
--     instance -- and they return zero rows. Measured: `SELECT COUNT(*) FROM
--     APPS.PA_PROJECTS_ALL` = 0, `COUNT(PROJECT_ID)` = 0, and likewise for
--     PA_TASKS, PA_BUDGET_VERSIONS and PA_BUDGET_LINES. (A projected
--     column-list read of PA_PROJECTS_ALL raised ORA-00942 against the same
--     synonym; the mechanism was not chased down because no reading of it
--     produces project data.) The emptiness is a property of the instance, not
--     of this sample.
--
--     The same emptiness was then confirmed from the other direction, which is
--     what closes the question. The two purchase-order tables that *do* carry
--     project columns on the live instance carry nothing in them: measured,
--     `PROJECT_ID` and `TASK_ID` are NULL on all 1,141,913 PO_LINES_ALL rows and
--     on all 1,159,988 PO_DISTRIBUTIONS_ALL rows. So there is no PO -> project
--     link to recover either. EBS Projects is not merely unpopulated at the
--     master; nothing anywhere points into it. Working note: PA_PROJECTS_ALL is
--     the only Projects table with a *real* shape on the live instance.
--
--     RESOLVED - WHERE PROJECTS WILL COME FROM. The owner of the data intends
--     to supply the project master as a SEPARATE SQLITE TABLE, populated by
--     their own process, rather than have it read back out of EBS. That is the
--     decision of record as of 2026-09-18 and it supersedes every earlier
--     reading of this section: no Oracle project query is to be written, and no
--     PA_* fetch is to be added. The three PA_* tables below are kept ONLY as a
--     shape for that future table to resemble -- PA_TASKS, PA_BUDGET_VERSIONS
--     and PA_BUDGET_LINES are still empty here and nothing reads them. When the
--     supplied table arrives it should be described in this section under its
--     real name and these rows replaced.
-- ============================================================================

CREATE TABLE IF NOT EXISTS PA_PROJECTS_ALL (
  PROJECT_ID          INTEGER PRIMARY KEY,
  PROJECT_NUMBER      TEXT,
  NAME                TEXT NOT NULL,
  PROJECT_TYPE        TEXT,
  PROJECT_STATUS_CODE TEXT,       -- 'APPROVED' / 'CLOSED'
  START_DATE          TEXT,
  COMPLETION_DATE     TEXT,
  ORG_ID              INTEGER,
  CARRYING_OUT_ORGANIZATION_ID INTEGER
);

CREATE TABLE IF NOT EXISTS PA_TASKS (
  TASK_ID        INTEGER PRIMARY KEY,
  PROJECT_ID     INTEGER NOT NULL,
  TASK_NUMBER    TEXT,
  TASK_NAME      TEXT,
  START_DATE     TEXT,
  COMPLETION_DATE TEXT,
  FOREIGN KEY (PROJECT_ID) REFERENCES PA_PROJECTS_ALL (PROJECT_ID)
);

CREATE TABLE IF NOT EXISTS PA_BUDGET_VERSIONS (
  BUDGET_VERSION_ID INTEGER PRIMARY KEY,
  PROJECT_ID        INTEGER NOT NULL,
  VERSION_NUMBER    INTEGER,
  VERSION_NAME      TEXT,
  CURRENT_FLAG      TEXT DEFAULT 'N',
  STATUS_CODE       TEXT,
  CREATION_DATE     TEXT,
  FOREIGN KEY (PROJECT_ID) REFERENCES PA_PROJECTS_ALL (PROJECT_ID)
);

CREATE TABLE IF NOT EXISTS PA_BUDGET_LINES (
  BUDGET_VERSION_ID INTEGER NOT NULL,
  LINE_NUM          INTEGER NOT NULL,
  TASK_ID           INTEGER,
  RESOURCE_LIST_MEMBER_ID INTEGER,
  RAW_COST          REAL NOT NULL DEFAULT 0,
  BURDENED_COST     REAL NOT NULL DEFAULT 0,
  PRIMARY KEY (BUDGET_VERSION_ID, LINE_NUM),
  FOREIGN KEY (BUDGET_VERSION_ID) REFERENCES PA_BUDGET_VERSIONS (BUDGET_VERSION_ID)
);


-- ============================================================================
--  5. (RETIRED) WCSEXP_* compatibility views.
--
--     An earlier revision of this schema defined 18 WCSEXP_* views over the real
--     tables, so that a query written against data/oracle/db-schema.md would
--     resolve without renaming anything. They have been REMOVED, deliberately.
--
--     Why. The Oracle originals in data/sql/*.sql and the ports in
--     data/sql/turso/queries/*.sql now read the base tables directly, which is
--     what the real extract grants expose. Keeping the views would give every
--     object two names and let the two halves drift apart - and the views were
--     never a pure pass-through, so a query could behave differently depending
--     on which name it used.
--
--     Removing them is what surfaced the three places the extract's vocabulary
--     differed from the tables. Those now live as comments in the queries rather
--     than as synthetic columns:
--       * GL_BALANCES.LEDGER_ID                     was aliased SET_OF_BOOKS_ID
--       * AP_INVOICE_DISTRIBUTIONS_ALL.CODE_COMBINATION_ID
--                                                   was aliased DIST_CODE_COMBINATION_ID
--       * AP_INVOICE_PAYMENTS_ALL.PAYMENT_DATE      was aliased CHECK_DATE
--
--     Two columns the views synthesised as NULL - POSTED_FLAG on a distribution,
--     and PO_DISTRIBUTION_ID on an AP invoice line - do NOT exist on the base
--     tables. data/sql/04-spend-and-actuals.sql documents what replaces each.
-- ============================================================================


-- ============================================================================
--  6. Reporting views — the report's derived columns, computed NOT stored.
--     report-findings.md section 3 proves Available Funds, GMP-Total and $/SF are
--     derived in the report rather than read from a table. Reproducing them as
--     views keeps that true: do not go looking for them as columns.
-- ============================================================================

-- Per account, per budget version: is it funded, and by how much net?
-- Uses the reference join through V_CODE_COMBINATION_KEY so a chart-of-accounts
-- change does not silently mis-join.
CREATE VIEW IF NOT EXISTS V_BUDGET_BY_ACCOUNT_PERIOD AS
  SELECT gb.LEDGER_ID,
         gb.CODE_COMBINATION_ID,
         cc.SEGMENT1, cc.SEGMENT2, cc.SEGMENT3, cc.SEGMENT4,
         cc.SEGMENT5, cc.SEGMENT6, cc.SEGMENT7,
         gb.BUDGET_VERSION_ID,
         gb.PERIOD_YEAR,
         gb.PERIOD_NUM,
         gb.PERIOD_NAME,
         SUM(gb.PERIOD_NET_DR - gb.PERIOD_NET_CR) AS NET_AMOUNT,
         COUNT(*)                                AS BALANCE_ROWS
    FROM GL_BALANCES gb
    JOIN GL_CODE_COMBINATIONS cc
      ON cc.CODE_COMBINATION_ID = gb.CODE_COMBINATION_ID
   WHERE gb.ACTUAL_FLAG         = 'B'
     AND gb.TRANSLATED_FLAG     = 'N'
     AND gb.ENCUMBRANCE_TYPE_ID IS NULL
     AND gb.LEDGER_ID IN (SELECT LEDGER_ID FROM GL_LEDGERS WHERE LEDGER_CATEGORY_CODE = 'PRIMARY')
     AND cc.SUMMARY_FLAG        = 'N'
     AND cc.ENABLED_FLAG        = 'Y'
   GROUP BY gb.LEDGER_ID, gb.CODE_COMBINATION_ID, gb.BUDGET_VERSION_ID,
            gb.PERIOD_YEAR, gb.PERIOD_NUM, gb.PERIOD_NAME,
            cc.SEGMENT1, cc.SEGMENT2, cc.SEGMENT3, cc.SEGMENT4,
            cc.SEGMENT5, cc.SEGMENT6, cc.SEGMENT7;

-- Available Funds = Allocations - Encumbrances - Expenditures, per account.
-- This is the report's own formula, verified on all four grid rows by
-- report-findings.md section 3. It is DERIVED here on purpose -- the report
-- computes it rather than reading it, so this view must too.
--
-- INTERPRETATION, NOT VERIFIED FACT. The report shows two different budget
-- figures per account ("WCPSS Budget" and "Allocations/Reimb."). Nothing in the
-- extracts says how Oracle distinguishes them. This models the distinction by
-- BUDGET TYPE, which is the only version-scoped axis the objects actually offer:
--     BUDGET_TYPE 2 ('CAPITAL') -> WCPSS Budget   (the budgeted amount)
--     BUDGET_TYPE 1 ('APPROP')  -> Allocations    (the funding allocated)
-- If that reading is wrong, this one view is wrong and nothing else is --
-- which is exactly why it is a view and not a column. Confirm before relying on it.
CREATE VIEW IF NOT EXISTS V_ACCOUNT_POSITION AS
  SELECT cc.CODE_COMBINATION_ID,
         cc.SEGMENT4 AS OBJECT_CODE,
         cc.SEGMENT5 AS LEVEL_CODE,
         cc.SEGMENT1||'.'||cc.SEGMENT2||'.'||cc.SEGMENT3||'.'||cc.SEGMENT4||'.'||
         cc.SEGMENT5||'.'||cc.SEGMENT6||'.'||cc.SEGMENT7 AS BUDGET_ACCOUNT,
         IFNULL(cap.BUDGET,      0) AS WCPSS_BUDGET,
         IFNULL(app.ALLOCATIONS, 0) AS ALLOCATIONS_REIMB,
         IFNULL(e.ENCUMBRANCES,  0) AS ENCUMBRANCES,
         IFNULL(a.EXPENDITURES,  0) AS EXPENDITURES,
         IFNULL(app.ALLOCATIONS,0) - IFNULL(e.ENCUMBRANCES,0) - IFNULL(a.EXPENDITURES,0)
           AS AVAILABLE_FUNDS
    FROM GL_CODE_COMBINATIONS cc
    LEFT JOIN (
      -- WCPSS Budget: the CAPITAL budget versions.
      SELECT gb.CODE_COMBINATION_ID,
             SUM(gb.PERIOD_NET_DR - gb.PERIOD_NET_CR) AS BUDGET
        FROM GL_BALANCES gb
        JOIN GL_BUDGET_VERSIONS bv ON bv.BUDGET_VERSION_ID = gb.BUDGET_VERSION_ID
        JOIN GL_BUDGET_TYPES    bt ON bt.BUDGET_TYPE_ID    = bv.BUDGET_TYPE_ID
       WHERE gb.ACTUAL_FLAG='B' AND gb.TRANSLATED_FLAG='N'
         AND gb.ENCUMBRANCE_TYPE_ID IS NULL
         AND bt.BUDGET_TYPE_CODE='CAPITAL'
         AND gb.LEDGER_ID IN (SELECT LEDGER_ID FROM GL_LEDGERS WHERE LEDGER_CATEGORY_CODE='PRIMARY')
       GROUP BY gb.CODE_COMBINATION_ID
    ) cap ON cap.CODE_COMBINATION_ID = cc.CODE_COMBINATION_ID
    LEFT JOIN (
      -- Allocations / Reimbursements: the APPROPRIATION budget versions.
      SELECT gb.CODE_COMBINATION_ID,
             SUM(gb.PERIOD_NET_DR - gb.PERIOD_NET_CR) AS ALLOCATIONS
        FROM GL_BALANCES gb
        JOIN GL_BUDGET_VERSIONS bv ON bv.BUDGET_VERSION_ID = gb.BUDGET_VERSION_ID
        JOIN GL_BUDGET_TYPES    bt ON bt.BUDGET_TYPE_ID    = bv.BUDGET_TYPE_ID
       WHERE gb.ACTUAL_FLAG='B' AND gb.TRANSLATED_FLAG='N'
         AND gb.ENCUMBRANCE_TYPE_ID IS NULL
         AND bt.BUDGET_TYPE_CODE='APPROP'
         AND gb.LEDGER_ID IN (SELECT LEDGER_ID FROM GL_LEDGERS WHERE LEDGER_CATEGORY_CODE='PRIMARY')
       GROUP BY gb.CODE_COMBINATION_ID
    ) app ON app.CODE_COMBINATION_ID = cc.CODE_COMBINATION_ID
    LEFT JOIN (
      SELECT CODE_COMBINATION_ID, SUM(PERIOD_NET_DR - PERIOD_NET_CR) AS ENCUMBRANCES
        FROM GL_BALANCES
       WHERE ACTUAL_FLAG='E' AND TRANSLATED_FLAG='N'
         AND LEDGER_ID IN (SELECT LEDGER_ID FROM GL_LEDGERS WHERE LEDGER_CATEGORY_CODE='PRIMARY')
       GROUP BY CODE_COMBINATION_ID
    ) e ON e.CODE_COMBINATION_ID = cc.CODE_COMBINATION_ID
    LEFT JOIN (
      SELECT CODE_COMBINATION_ID, SUM(PERIOD_NET_DR - PERIOD_NET_CR) AS EXPENDITURES
        FROM GL_BALANCES
       WHERE ACTUAL_FLAG='A' AND TRANSLATED_FLAG='N'
         AND LEDGER_ID IN (SELECT LEDGER_ID FROM GL_LEDGERS WHERE LEDGER_CATEGORY_CODE='PRIMARY')
       GROUP BY CODE_COMBINATION_ID
    ) a ON a.CODE_COMBINATION_ID = cc.CODE_COMBINATION_ID
   WHERE (app.CODE_COMBINATION_ID IS NOT NULL OR cap.CODE_COMBINATION_ID IS NOT NULL)
     AND cc.SUMMARY_FLAG = 'N'
     AND cc.ENABLED_FLAG = 'Y';

-- The segment legend: which level codes have a name and which do not.
-- "Unnamed" is a real, reportable state.
CREATE VIEW IF NOT EXISTS V_SEGMENT_LEGEND AS
  SELECT cc.SEGMENT5 AS LEVEL_CODE,
         COUNT(*)    AS ACCOUNT_COUNT,
         MAX(fv.DESCRIPTION) AS LEVEL_NAME
    FROM GL_CODE_COMBINATIONS cc
    LEFT JOIN FND_FLEX_VALUES fv
      ON fv.FLEX_VALUE_SET_ID = 10101
     AND fv.FLEX_VALUE        = cc.SEGMENT5
   WHERE cc.SEGMENT5 IS NOT NULL AND cc.SEGMENT5 <> ''
   GROUP BY cc.SEGMENT5;

-- Encumbrances as computed from the PURCHASING extract, independent of
-- GL_BALANCES. This exists because the two WILL NOT AGREE, and the disagreement
-- is a fact about the data rather than a bug:
--   the extract in data/oracle/ is a partial slice, so it never contains every
--   transaction behind the report. The report's level-0450 account for object 526
--   is not even present in the COA extract, and only one level-0450 account is.
-- Keep BOTH numbers side by side. Where they differ is exactly where the slice
-- is incomplete, and that is information rather than noise.
CREATE VIEW IF NOT EXISTS V_ENCUMBRANCE_FROM_PO AS
  SELECT pd.CODE_COMBINATION_ID,
         cc.SEGMENT4 AS OBJECT_CODE,
         cc.SEGMENT5 AS LEVEL_CODE,
         COUNT(DISTINCT pd.PO_DISTRIBUTION_ID) AS DISTRIBUTIONS,
         SUM(IFNULL(pd.ENCUMBERED_AMOUNT,0))   AS ENCUMBERED_FROM_PO,
         SUM(IFNULL(pd.AMOUNT_ORDERED,0))      AS ORDERED_FROM_PO
    FROM PO_DISTRIBUTIONS_ALL pd
    JOIN GL_CODE_COMBINATIONS cc ON cc.CODE_COMBINATION_ID = pd.CODE_COMBINATION_ID
   WHERE pd.ENCUMBERED_FLAG = 'Y'
   GROUP BY pd.CODE_COMBINATION_ID, cc.SEGMENT4, cc.SEGMENT5;


-- ============================================================================
--  7. X_* — NON-EBS tables. Held here because they have no standard EBS home.
--
--  The X_ prefix is deliberate and load-bearing: anything named X_ is NOT an
--  Oracle EBS object and must never be mistaken for one. report-findings.md
--  section 1 establishes that the report's construction-planning block (CCAP,
--  GMP-Building, GMP-Site, GSF, $/SF, Bid/NTP/SC/FC) and its forward-year
--  funding rows have NO standard EBS home — they are custom-table or DFF data.
--  Modelling them as EBS objects would make this schema claim coverage it does
--  not have, so they are quarantined behind the prefix instead.
-- ============================================================================

-- The report's funding block, transcribed. Project-level, so it does NOT
-- reconcile with the per-account GL_BALANCES allocations and is not expected to.
-- Two different grains of the same story: funding is authorised at the project,
-- budgets are held per account.
CREATE TABLE IF NOT EXISTS X_REPORT_FUNDING_LINES (
  LINE_NUM     INTEGER PRIMARY KEY,
  DESCRIPTION  TEXT    NOT NULL,
  AMOUNT       REAL    NOT NULL,
  ANNOTATION   TEXT,               -- 'BOE 7/13/2022' / 'Est. 8/20/2026'
  EVENT_DATE   TEXT,               -- parsed from ANNOTATION, 'YYYY-MM-DD'
  FISCAL_YEAR  INTEGER,
  IS_FORECAST  INTEGER NOT NULL DEFAULT 0,  -- 1 for the 'Est.' rows
  IN_FUNDING_TOTAL INTEGER NOT NULL DEFAULT 1
);

-- The report's construction-planning block, transcribed. No EBS object backs
-- these. Kept so the report is reproducible end to end; treat as decorative
-- until a real source is found.
CREATE TABLE IF NOT EXISTS X_REPORT_PROJECT_FACTS (
  FACT_NAME   TEXT PRIMARY KEY,
  FACT_VALUE  TEXT,
  UNIT        TEXT,
  NOTE        TEXT
);
